language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
before_install: "gem update --system"

cache: bundler
sudo: false
dist: trusty

env:
  - CI=true RACK_VERSION=1.6
  - CI=true RACK_VERSION=2.0

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9
  - rbx-3

matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: rbx-3
    - rvm: ruby-head
