language: ruby
script: "bundle exec rspec spec"
cache: bundler
sudo: false
dist: trusty
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head
